apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: deployment-otelcol
  namespace: opentelemetry
  labels:
    app.kubernetes.io/name: deployment-otelcol
spec:
  image: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib"
  mode: deployment
  hostNetwork: false
  envFrom:
    - secretRef:
        name: otel-secret
    - configMapRef:
        name: otel-config
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      k8s_cluster:
        collection_interval: 10s
    processors:
      batch:
        send_batch_size: 1000
        send_batch_max_size: 5000
        timeout: 5s
    exporters:
      debug:
        verbosity: detailed
      splunk_hec/metrics:
        token: ${env:SPLUNK_HEC_TOKEN}
        endpoint: ${env:SPLUNK_HEC_ENDPOINT}
        index: "otlp-metrics"
        tls:
          insecure_skip_verify: true
      splunk_hec/logs:
        token: ${env:SPLUNK_HEC_TOKEN}
        endpoint: ${env:SPLUNK_HEC_ENDPOINT}
        index: "otlp-logs"
        tls:
          insecure_skip_verify: true
      splunk_hec/traces:
        token: ${env:SPLUNK_HEC_TOKEN}
        endpoint: ${env:SPLUNK_HEC_ENDPOINT}
        index: "otlp-traces"
        tls:
          insecure_skip_verify: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [splunk_hec/traces]
        metrics:
          receivers: [otlp,k8s_cluster]
          processors: [batch]
          exporters: [splunk_hec/metrics]
        logs:
          receivers: [otlp,k8s_cluster]
          processors: [batch]
          exporters: [splunk_hec/logs]