apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: daemonset-otelcol
  namespace: opentelemetry
  labels:
    app.kubernetes.io/name: daemonset-otelcol
spec:
  image: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
  mode: daemonset
  hostNetwork: false
  envFrom:
    - secretRef:
        name: otel-secret
    - configMapRef:
        name: otel-config
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      kubeletstats:
        collection_interval: 10s
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        auth_type: "serviceAccount"
        insecure_skip_verify: true
        # Tells the receiver to explicitly extract pod and container metrics
        metric_groups:
          - pod
          - container

    processors:
      batch:
        send_batch_size: 1000
        send_batch_max_size: 5000
        timeout: 5s
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.uid
      
    exporters:
      debug:
        verbosity: detailed
      splunk_hec/metrics:
        token: ${env:SPLUNK_HEC_TOKEN}
        endpoint: ${env:SPLUNK_HEC_ENDPOINT}
        index: "otlp-metrics"
        tls:
          insecure_skip_verify: true
      splunk_hec/logs:
        token: ${env:SPLUNK_HEC_TOKEN}
        endpoint: ${env:SPLUNK_HEC_ENDPOINT}
        index: "otlp-logs"
        tls:
          insecure_skip_verify: true

    service:
      pipelines:
        metrics:
          receivers:
            - otlp
            - kubeletstats
          processors:
            - k8sattributes
            - batch
          exporters: [splunk_hec/metrics]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [splunk_hec/logs]